### ISSUE TITLE
Hit assertion "Use still stuck ..." when compiling kernel

### ISSUE THREAD

**Issue by j-schulte** [google/clspv#142]
When compiling the attached kernel ([assertion.txt](https://github.com/google/clspv/files/2072886/assertion.txt)) with Clspv, the compilation aborts with the following output:

> While deleting: i8* %
> Use still stuck around after Def is destroyed:  call void @llvm.lifetime.end.p0i8(i64 128, i8* nonnull <badref>)
> Use still stuck around after Def is destroyed:  call void @llvm.lifetime.start.p0i8(i64 128, i8* nonnull <badref>)
> clspv: ../third_party/llvm/lib/IR/Value.cpp:86: llvm::Value::~Value(): Assertion `use_empty() && "Uses remain when a value is destroyed!"' failed.
> Aborted (core dumped)`

Regards
Johannes

**Comment by dneto0** [comment]
This has been fixed with an update about 2 weeks ago.

I'm attaching the generates SPIR-V assembly
[assert.spvasm.txt](https://github.com/google/clspv/files/2104162/assert.spvasm.txt)

**Comment by johannesschulte** [comment]
I'm sorry, I forgot to mention that I'm running clspv with "-pod-ubo -cluster-pod-kernel-args". With these options, the error persists.

**Comment by j-schulte** [comment]
I'm sorry, I forgot to mention that I'm running clspv with "-pod-ubo -cluster-pod-kernel-args". With these flags, the error persists.

**Comment by dneto0** [comment]
Reproduces with just -cluster-pod-kernel-args

**Comment by dneto0** [comment]
Thanks for the high quality bug report.

**Comment by j-schulte** [comment]
Thanks for the quick fixes!
